echo "Sourcing ~/.zshrc"

export INCLUDES_DIR=~/codez/dot-files/dot_zshrc/includes
for include in `/bin/ls -1 $INCLUDES_DIR`
do
        echo "Sourcing $include..."
        source "$INCLUDES_DIR/$include"
done

export GOPATH=$HOME/go
PATH=$PATH:${GOPATH//://bin:}/bin
