# The .zshrc file, for reference.
export ZDOTDIR=~/codez/dot-files/dot_zshrc/includes

for i in `/bin/ls -1 $ZDOTDIR`
do
        echo "Sourcing $i..."
        source "$ZDOTDIR/$i"
done

export PATH="$HOME/.yarn/bin:$PATH"
