set nocompatible

filetype off                   " required!

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
" required!
Plugin 'VundleVim/Vundle.vim'

" set the <Leader> binding to something easy to reach
let mapleader = ","

":echom "source bundles"
source $DOT_FILES_DIR/dot_vimrc/bundles.vim

" All of your Plugins must be added before the following line
call vundle#end()            " required

" load the plugin and indent settings for the detected filetype
filetype plugin indent on     " required!

" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

set encoding=utf-8

":echom "source includes"
for f in split(glob('$DOT_FILES_DIR/dot_vimrc/includes/*.vim'), '\n')
  exe 'source' f
endfor
":echom "vimrc done"
